# Workflow의 이름
name: Github Actions 실행시켜보기

# Event: 실행되는 시점을 설정
# main이라는 브랜치에 push될 때 아래 workflow를 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 job으로 구성
# Job: 작업 단위
jobs:
  # 여러 Job은 기본적으로 병렬로 수행된다.
  # Job을 식별하기 위한 Id
  My-Deploy-Job:
    # 환경 설정: ubuntu, latest version (가장 최신)
    runs-on: ubuntu-latest
    # Step: 특정 작업(Job)을 수행하는 가장 작은 단위
    # Job은 여러 Step들로 구성되어 있다.
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명렁어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"

      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 외부에 노출이 되면 안 되는 값
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}